### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by maxindelicato** [helsing/valid4j#3]
Hello, I'm interested in taking this project over and continuing development on it. Is that a possibility? Thanks.

**Comment by segfly** [comment]
@maxindelicato I was wondering the same thing. My team use this library extensively, and we've never had any issue with it, even though the last release was in 2015. I think that's a testimate to how well it was initially designed. Even so, it'd be nice to see some new features while keeping it lean.

It would be a shame to have to fork this project to get it moving again. I see @helsing , @guranxp , and @gorper in the commit history. Maybe on of them are still around? Unfortunately they don't seem to have made any commits in a very long time.

**Comment by helsing** [comment]
Hi both, sorry for late reply. Yes, you are correct in that this project is not very active, although the library itself is widely used at my company and elsewhere. That being said, I would be more than happy to help out with any features you would like to see added. What did you have in mind?

**Comment by segfly** [comment]
For the most part, I am more concerned with the perception that the project is dead. Because if there have been no recent commits it is my experience people usually will be wary of adopting, as they don't want to be caught using an "old" or "unsupported" library. Valid4j is very mature and robust in my opinion, and it would be a shame if that is the one thing that turns people away.

Beyond that, there is #2 that could be interesting. While I don't agree that "hamcrest is old" is a valid reason not to use it, if there is something better that has a lot of adoption it may be worth a look:
https://www.blazemeter.com/blog/hamcrest-vs-assertj-assertion-frameworks-which-one-should-you-choose/

**Comment by helsing** [comment]
I _do_ agree that automatic code completion is a good feature from the AssertJ approach. 

That being said, the AssertJ design doesn't make it easily extensible since you are more less required to include the extensions via statically build it into the assertion class(es). The hamcrest approach separates the concerns, i.e the assertion semantics is totally independent from the condition/predicate/describer logic, which lays the foundation for separation of development paths. You can use any Hamcrest matcher from any 3rd party library together with valid4j. You can't reuse anything from the AssertJ world, without implementing all of their DSL in a valid4j flavor.

However, I am open to review and include any good design approaches to solve this problem. Bring it on! :-)
